[project]
name = "adk-web-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "google-adk>=1.0.0",
]

[tool.uv.workspace]
members = [
    "adk_multiagent_mcp_app/mcp_server",
]
